#!/bin/bash

#SBATCH --job-name shelfbreak  # jobname
#SBATCH --mail-type=ALL  #Mail events (BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=galen.wilcox@whoi.edu  # Where to send email
#SBATCH --nodes=8                      # Number of nodes
##SBATCH --ntasks-per-node=36          # How many tasks on each node

#SBATCH --partition=compute,scavenger #Queue selection, compute,scavenger vs. interactive

#SBATCH --ntasks=288                   # Number of MPI ranks
#SBATCH --cpus-per-task=1             # Number of cores per MPI rank

#SBATCH --mem-per-cpu=2gb 
#SBATCH --time=23:59:00               # Time limit hrs:min:sec
##SBATCH --time=00:59:00               # Time limit hrs:min:sec
#SBATCH --output=gcmOut%j.log      # Standard output/error

#SBATCH --exclusive
#SBATCH --exclude=pn[006,010,011,031,035,074,081-084,105-107,109,135,136]

#module load intel/2018 openmpi/intel/3.0.1 netcdf/intel/4.6.1
module load openmpi/intel/3.0.1

#cp -r ../runtime_files ../runtime_files_clean
mpirun --mca btl_vader_fbox_max 0 -np 288 /proj/wzhang/gwilcox/MITgcm_projects/pisces/shelfbreak1/buildSB/mitgcmuv
